version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: handmade_crafts
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
    - ./assets/handmade_crafts.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
